spring:
  application:
    name: spring-full-features
  profiles:
    active: dev

  redis:
    port: 6379 #Redis服务器连接的端口
    host: 47.244.38.108 # Redis服务器的地址
    database: 0 # Redis数据库索引（默认为0
    password: # Redis服务器连接密码（默认为空）
    timeout: 5000ms # 连接超时时间（毫秒）

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true